name: test-lid-deploy-action

on: [push]

env:
  envproduct: crt-backend

jobs:
  canary:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: ${{ process.env.envproduct }}
        fabric: corp-lca1
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3
    
    - name: Output Action Execution Result
      run: echo "Deployment execution result is ${{ steps.canary.outputs.execution_response }}"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

  ekg:

    runs-on: ubuntu-latest

    steps:
    - name: Output Action Execution Result for Prev. Job
      run: echo "Deployment execution result is ${{ steps.canary.outputs.execution_response }}"