name: test-deploy-to-multiple-clusters

on: [push]

# context:
#   linkedin:
#     range:
#       colo: %PROD
#       clusters: %ESPRESSO_CLUSTERS

# github:
#   # envproduct: ${{ linkedin.range.%%PROD }}
#   berlo: [prod-lva1, prod-ltx1]

jobs:
  lsg1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cluster: join(${{ linkedin.range.%espresso-tiers:TIER2 }}, ${{ linkedin.range.%espresso-tiers:TIER1 }})
      max-parallel: 2
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: espresso
        fabric: prod-lsg1
        tag: ${{ matrix.cluster }}
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3

    - name: Promotion
      run: echo "I am going to promote"

  
  lva1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cluster: join(${{ linkedin.range.%espresso-tiers:TIER2 }}, ${{ linkedin.range.%espresso-tiers:TIER1 }})
      max-parallel: 2
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: espresso
        fabric: prod-lva1
        tag: ${{ matrix.cluster }}
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3

    - name: Promotion
      run: echo "I am going to promote"
    
  lsg1-tier0:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cluster: ${{ linkedin.range.%espresso-tiers:TIER0 }}
      max-parallel: 2
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: espresso
        fabric: prod-lsg1
        tag: ${{ matrix.cluster }}
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3

    - name: Promotion
      run: echo "I am going to promote"
  
  lva1-tier0:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cluster: ${{ linkedin.range.%espresso-tiers:TIER0 }}
      max-parallel: 2
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: espresso
        fabric: prod-lva1
        tag: ${{ matrix.cluster }}
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3

    - name: Promotion
      run: echo "I am going to promote"