name: test-deploy-to-multiple-clusters

on: [push]

env:
  envproduct: crt-backend

jobs:
  canary:
    strategy:
      matrix:
        colo: [prod-lva1, prod-ltx1]
        cluster: [cluster1, cluster2]
      max-parallel: 2

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: espresso
        fabric: ${{ matrix.colo }}
        tag: ${{ matrix.cluster }}
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3
    
    - name: Output Action Execution Result
      run: echo "Deployment execution result is ${{ steps.canary.outputs.execution_response }}"

    - name: Promotion
      run: echo "I am going to promote"