name: test-lid-deploy-action

on: [push]

env:
  envproduct: crt-backend

jobs:
  canary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: canary
      uses: ./actions/lid-deploy
      id: canary
      with:
        product: crt-backend
        fabric: corp-lca1
        beta_version: 0.0.2
        base_version: 0.0.1
        ramp_percentage: 0.3
    
    - name: Output Action Execution Result
      run: echo "Deployment execution result is ${{ steps.canary.outputs.execution_response }}"

  ekg:
    runs-on: ubuntu-latest

    needs: canary

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Output Action Execution Result of Prev. Job
      run: echo "Deployment execution result is ${{ job.canary.steps.canary.outputs.execution_response }}"

    - name: ekg
      uses: ./actions/any-action
      id: ekg
      with:
        anyinput: PASS
        additionalinput: GOOD
    
    - name: Output EKG Result
      run: echo "EKG result is ${{ steps.ekg.outputs.anyoutput }}"

    - name: sleep
      uses: ./actions/sleep
      with:
        time-in-seconds: 5

    - name: This shouldn't be run
      if: cancelled()
      run: echo 'Workflow is cancelled'